### ISSUE TITLE
Unexpected messages viewing Uncategorised

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/fizzie#21]
In a brand new WordPress Multi Site site I visited 
https://s.b/wp55/fizzie/category/uncategorised/
and got the following:

Notice: Trying to get property 'term_id' of non-object in C:\apache\htdocs\wp55\wp-content\plugins\gutenberg\build\block-library\blocks\post-hierarchical-terms.php on line 32

Notice: Trying to get property 'name' of non-object in C:\apache\htdocs\wp55\wp-content\plugins\gutenberg\build\block-library\blocks\post-hierarchical-terms.php on line 33

```
Fatal error: Uncaught Error: Object of class WP_Error could not be converted to string in 
C:\apache\htdocs\wp55\wp-content\plugins\gutenberg\build\block-library\blocks\post-hierarchical-terms.php:33 
Stack trace: 
#0 C:\apache\htdocs\wp55\wp-content\plugins\gutenberg\build\block-library\blocks\post-hierarchical-terms.php(33): sprintf('<a href="%1$s">...', Object(WP_Error), '') 
#1 C:\apache\htdocs\wp55\wp-includes\class-wp-block.php(219): gutenberg_render_block_core_post_hierarchical_terms(Array, '', Object(WP_Block)) 
#2 C:\apache\htdocs\wp55\wp-includes\class-wp-block.php(211): WP_Block->render() 
#3 C:\apache\htdocs\wp55\wp-includes\class-wp-block.php(211): WP_Block->render() 
#4 C:\apache\htdocs\wordpress\wp-content\themes\fizzie\functions.php(278): WP_Block->render(Array) 
#5 C:\apache\htdocs\wordpress\wp-content\themes\fizzie\functions.php(234): fizzie_render_block_core_query_loop_main_query(Array, '', Object(WP_Block)) 
#6 C:\apache\htdocs\wp55\wp-includes\class-wp-block.php(219): fizzie_render_block_core_query_loop(Array, in C:\apache\htdocs\wp55\wp-content\plugins\gutenberg\build\block-library\blocks\post-hierarchical-terms.php on line 33
```

**Comment by bobbingwide** [comment]
This no longer occurs; `core/post-hierarchical-terms` was replaced by `core/post-terms` in Gutenberg 10.6.0
