### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function bw_get_field_names()

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/fizzie#50]
Fatal error: Uncaught Error: Call to undefined function bw_get_field_names() in C:\apache\htdocs\wordpress\wp-content\plugins\oik-fields\shortcodes\oik-fields.php:74 

```
Stack trace: 
#0 C:\apache\htdocs\wordpress\wp-content\plugins\oik-blocks\oik-blocks.php(322): bw_metadata(Array, NULL, NULL) 
#1 C:\apache\htdocs\wp55\wp-includes\class-wp-block.php(221): oik_blocks_dynamic_block_fields(Array, '', Object(WP_Block)) 
#2 C:\apache\htdocs\wp55\wp-includes\class-wp-block.php(211): WP_Block->render() 
#3 C:\apache\htdocs\wp55\wp-content\plugins\gutenberg\lib\compat.php(452): WP_Block->render() 
#4 C:\apache\htdocs\wp55\wp-includes\class-wp-hook.php(287): gutenberg_render_block_with_assigned_block_context(NULL, Array) 
#5 C:\apache\htdocs\wp55\wp-includes\plugin.php(212): WP_Hook->apply_filters(NULL, Array) 
#6 C:\apache\htdocs\wp55\wp-includes\blocks.php(672): apply_filters('pre_render_bloc...', NULL, Array) 
#7 C:\apache\htdocs\wp55\wp-includes\blocks.php(760): render_block(Array) 
#8 C:\apache\htdocs\wordpress\wp-content\themes\fizzie\i in C:\apache\htdocs\wordpress\wp-content\plugins\oik-fields\shortcodes\oik-fields.php on line 74

**Comment by bobbingwide** [comment]
This is a problem due to the `oik-blocks` plugin loading the file even though the plugin isn't activated. 
There's a @TODO in oik-blocks to check that the plugin's active. Raising issue against oik-blocks.
